#' @param datacategoryid Accepts a valid data category id or an array of data category ids. 
#'    Stations returned will be associated with the data category(ies) specified (optional)
#' @param extent The geographical extent for which you want to search. Designed to take a 
#'    parameter generated by Google Maps API V3 LatLngBounds.toUrlValue. Stations returned 
#'    must be located within the extent specified (optional)
#' @param dataset THIS IS A DEPRECATED ARGUMENT. See datasetid.
#' @param station THIS IS A DEPRECATED ARGUMENT. See stationid.
#' @param location THIS IS A DEPRECATED ARGUMENT. See locationid.
#' @param locationtype THIS IS A DEPRECATED ARGUMENT. There is no equivalent argument in v2 
#'    of the NOAA API.
#' @param page THIS IS A DEPRECATED ARGUMENT. There is no equivalent argument in v2 
#'    of the NOAA API.