vignettes:
	    Rscript -e 'library(knitr); knit("rnoaa_vignette.Rmd")'
	    pandoc -H margins.sty rnoaa_vignette.md -o rnoaa_vignette.html
	    pandoc -H margins.sty rnoaa_vignette.md -o rnoaa_vignette.pdf