---
title: "Test case: Alaska wildfires"
author: Brooke Anderson (BA), Sheryl Magzamen (SM), Ryan Gan (RG)
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Main task 

You are trying to get observational data related to wildfires from throughout the state of Alaska for the years 2000-2016. 

# Relevant NOAA weather products

In later sections, you will have specific goals to try to achieve, in terms of what data to get. However, as you work on this project, please keep a running list here of any of the NOAA data products that you think might have data that could be used to explore the storm you're working on. Include the name of the dataset, a short description of what you might be able to get from it, and a link to any websites that give more information.

# Relevant other data sources

As you work on this project, also keep a running list here of any data from sources other than NOAA that you think might have data that could be used to explore the storm you're working on. Include the name of the dataset, a short description of what you might be able to get from it, and a link to any websites that give more information and / or the data itself.

- SM: There’s some data from the Alaska Interagency Coordination Center on lightning strikes and wildfires: http://wildfiretoday.com/2015/06/23/alaska-46000-lightning-strikes-and-many-fires/
- SM: Vegetation is usually USDA and NDVI is a NOAA product (http://earthobservatory.nasa.gov/Features/MeasuringVegetation/measuring_vegetation_2.php)

# Specific tasks

As you work on these, include the code that you try. Include things that worked and things that you thought would work but that did not. Also write down what parts were easy to figure out how to do, and which you had to search around a lot to figure out what to do. 

## Lightning strikes

Get a dataset of lightning strikes within Alaska for 2000-2016, with the following columns: 

- Date / time: The date and, if available, time of the lightning strike
- Latitude: The latitude of the strike, in decimal degrees North
- Longitude: The longitude of the strike, in decimal degrees West

Are there any other variables available for each strike? If so, please describe what any other variables measure and include them in your dataframe. 

How many lightning strikes did you record in Alaska over this time period? Create a map by year of lightning strike locations. If you can, also create a heatmap, where you break the state up into either grid boxes or counties and show with color the number of lightning strikes per box / county over the time period. 

- BA: `rnoaa`'s `swdi` series of functions looks like it might have data on lightning strikes. The vignette for that series is [here](https://github.com/ropensci/rnoaa/blob/master/vignettes/swdi_vignette.Rmd). The NCDC webpage for the severe weather data inventory is [here](http://www.ncdc.noaa.gov/swdi/#Intro). From the documentation, it sounds like for non-military users, you may only be able to get number of strikes per day per region, not exact time and location.  
- BA: [Here](https://www.ncdc.noaa.gov/data-access/severe-weather/lightning-products-and-services) is some more information from NOAA on lightning strikes. I'm not clear yet on how much of this overlaps the SWDI resource. 

## Relevant weather measures

Get observed measurements for the following variables: 

- Air temperature
- A measure of air moisture (dew point temperature or relative humidity)
- Wind (speed and direction)

First, get these values at a daily resolution. Get a separate time series for each weather monitor in Alaska (although limit to just weather monitors that have non-missing observations for at least 95% of days over 2000-2016). Also aggregate these monitor time series by county to get county-level time series. 

For the first week of July 2015, get values for each of the weather variables, at as fine a time resolution as possible, for each lightning strike in Alaska. In other words, for a given lightning strike, get weather data from the closest available weather monitor. If you can get the exact time for a lightning strike, try to get the matching weather variables at an hourly or minute resolution at the time of the lightning strike. If you can only get daily counts for a region, get a daily aggregated value of the weather variables for all monitors in the region.

- BA: For daily data, you should be able to use `meteo_pull_monitors` from `rnoaa` to collect this data. However, you'll need to find all the weather stations IDs that you want to pull first. For that, you may want to try out `ncdc_stations`, using the `locationid` argument to get a list of stations either by county or by state. If you are pulling and aggregating by county, you can also use the `weather_fips` function from the `countyweather` package, which lets you pull data by county FIPS code. 

## Vegetation / NDVI

Gather the data on the vegetation / NDVI throughout Alaska. Do so at as fine of a temporal and spatial resolution as possible. If you can gather this at a very fine spatial and temporal resolution, start by only collecting for the first week of July 2015. If you can only get yearly values, get values for each year from 2000-2016. 
